### ISSUE TITLE
`stdin` context for replacement

### ISSUE THREAD

**Issue by attakei** [attakei/age-cli#12]
## Usecase

```toml
[[files]]
path = "CHANGES.md"
search = "# Changelog"
replace = """
# Changelog

## v{{ new_version }} - {{ now|date }}

{{ stdin }}
"""

```

```console
a-tool-to-generate-changelog-from-commits | age patch
```
