### ISSUE TITLE
Support regex replacement

### ISSUE THREAD

**Issue by attakei** [attakei/age-cli#8]
## Overview 

Currently, `release-body.md` is managed by age itself. (This is used on GitHub Releases)

`release-body.md` includes diff URL about current_version and new_version, but it cannot replace by age.

Settings ([from here]( https://github.com/attakei/age-cli/blob/v0.6.0/.age.toml)):

```toml
[[files]]
path = ".github/release-body.md"
search = "- Changelog is https://github.com/attakei/age-cli/blob/v{{current_version}}/CHANGELOG.md"
replace = "- Changelog is https://github.com/attakei/age-cli/blob/v{{new_version}}/CHANGELOG.md"
```

Output (from [here](https://github.com/attakei/age-cli/blob/v0.6.0/.github/release-body.md):

```markdown
Release updated `age` as built binary.

- Changelog is https://github.com/attakei/age-cli/blob/v0.6.0/CHANGELOG.md
- Source changes is https://github.com/attakei/age-cli/compare/v0.5.0...v0.6.0
```

`Source changes` have not also curren_version but **old_version** when running age-cli.
CLI cannot know what is previous version.

## Fix approach

Use regexp

Example:

```toml
[[files]]
path = ".github/release-body.md"
search = """
- Changelog is https://github.com/attakei/age-cli/blob/v{{current_version}}/CHANGELOG.md
- Source changes is (.+)
""""
replace = """
- Changelog is https://github.com/attakei/age-cli/blob/v{{new_version}}/CHANGELOG.md
- Source changes is https://github.com/attakei/age-cli/compare/v{{current_version}}...v{{new_version}}
"""
```

`search` has syntax of regexp.
If it includes regexp, writer use it instead of simple matching to search target.
